bitrise yml updated

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -4,8 +4,8 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: android
 trigger_map:
 - push_branch: master
-  workflow: primary
-- workflow: deploy
+  workflow: deploy
+- workflow: primary
   pull_request_target_branch: master
 workflows:
   deploy:
@@ -64,6 +64,19 @@ workflows:
         - project_location: "$PROJECT_LOCATION"
         - module: "$MODULE"
         - variant: "$VARIANT"
+    - script@1.1.5:
+        title: Gradle connected android test
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            echo "Hello World!"
+            ./gradlew "app:connectedAndroidTest"
     - android-build@0.10.0:
         inputs:
         - project_location: "$PROJECT_LOCATION"
@@ -72,6 +85,24 @@ workflows:
     - sign-apk@1.4.1:
         run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
     - deploy-to-bitrise-io@1.9.2: {}
+    - slack@3:
+        inputs:
+        - api_token: ''
+        - channel: channel ID:G010ZD1JZD3
+        - text: master push
+        - channel_on_error: channel ID:G010ZD1JZD3
+        - text_on_error: "$BITRISE_APP_TITLE"
+        - buttons: |
+            Descargar APK |${BITRISE_PUBLIC_INSTALL_PAGE_URL}
+            Ver detalles de App|${BITRISE_APP_URL}
+            Ver Build|${BITRISE_BUILD_URL}
+        - fields: |+
+            App|${BITRISE_APP_TITLE}
+            Branch|${BITRISE_GIT_BRANCH}
+            Workflow|${BITRISE_TRIGGERED_WORKFLOW_ID}
+
+        - message_on_error: ''
+        - webhook_url: "$SLACK_WEBHOOK"
     - cache-push@2.2.1: {}
   primary:
     steps:
@@ -129,11 +160,10 @@ workflows:
         inputs:
         - api_token: ''
         - channel: channel ID:G010ZD1JZD3
-        - text: ''
+        - text: master pull request
         - channel_on_error: channel ID:G010ZD1JZD3
         - text_on_error: "$BITRISE_APP_TITLE"
         - buttons: |
-            Descargar APK |${BITRISE_PUBLIC_INSTALL_PAGE_URL}
             Ver detalles de App|${BITRISE_APP_URL}
             Ver Build|${BITRISE_BUILD_URL}
         - fields: |+
